### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by g-scalvini** [pear/XML_HTMLSax3#4]
I'm probably doing something wrong, but executing test using this command:
 `./vendor/bin/phpunit --verbose tests`
using phpunit/phpunit 4.8.36 on PHP 5.6.40-66+ubuntu20.04.1+deb.sury.org+1
results in multiple errors:

> FAILURES!
> Tests: 26, Assertions: 18, Errors: 8, Failures: 18.

**Comment by ashnazg** [comment]
I don't think it's you... it looks like the testcases are written for SimpleTest, and will need to be migrated to proper PHPUnit before they will work.

**Comment by ashnazg** [comment]
@g-scalvini , I've updated the build structure and gotten the Travis builds running, at least paid builds on my fork.  If you want to try migrating the testcases from SimpleTest to PHPUnit, submit a PR and I'll check it out.
